-- Complete Customer Import for WearCheck
-- This replaces all existing customer data

-- First, update the customers table to include all fields
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_state VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS billing_country VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS shipping_state VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS shipping_country VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tax_reg_number VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS sage_id VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS registration_number VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 7);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 7);

-- Clear existing customers
TRUNCATE TABLE customers RESTART IDENTITY CASCADE;

-- Insert all customers
INSERT INTO customers (customer_number, display_name, currency_code, billing_city, billing_state, billing_country, shipping_city, shipping_state, shipping_country, vat_number, vat_treatment, email, region) VALUES
('CUS-00002', 'A Siwele General Services', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', NULL, 'vat_not_registered', 'giftmsimeki3@gmail.com', 'Local'),
('1SS504', 'ABACO Offshore Limited', 'USD', 'Kuala', 'Wilayah Persekutuan Kuala Lumpur', 'Malaysia', 'Löhne', NULL, 'Germany', NULL, 'overseas', 'gabriel.tungo@bumiarmada.com', 'Overseas'),
('CUS-00004', 'Abengoa Solar Power South Africa (Pty) Ltd - Xina O & M Company', 'ZAR', 'Cape Town', 'Western Cape', 'South Africa', 'Cape Town', 'Western Cape', 'South Africa', '4250279033', 'vat_registered', 'jodine.waterboer@abengoa.com', 'Local'),
('2SE106', 'AECI Mining Chemicals, a division of AECI Mining Ltd', 'ZAR', 'Sasolburg', 'Free State', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4140211857', 'vat_registered', 'neels.vanvuuren@aeciworld.com', 'Local'),
('1AF201', 'African Oxygen Limited t/a Afrox', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4120110541', 'vat_registered', NULL, 'Local'),
('2AI106', 'Air Liquide Large Industries (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, 'Belgium', '4480103177', 'vat_registered', NULL, 'Local'),
('CUS-00008', 'Air Products South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4020120673', 'vat_registered', 'sandiso.mngadi@airproducts.co.za', 'Local'),
('CUS-00009', 'Air Rotory Services (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4470274590', 'vat_registered', 'Retha@airrotoryservices.co.za', 'Local'),
('CUS-00010', 'Almec Manufacturing (Pty) Ltd', 'ZAR', 'Klerksdorp', 'North West', 'South Africa', 'Uraniaville', NULL, 'South Africa', '4300112838', 'vat_registered', 'heino@almecmanufacturing.co.za', 'Local'),
('CUS-00011', 'Ana-Digi Systems (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, 'Antwerpen', 'Belgium', '4160103661', 'vat_registered', 'hanneleze@anadigi.co.za', 'Local'),
('CUS-00012', 'Valterra Platinum Limited - Precious Metals Refineries', 'ZAR', 'Rustenburg', 'North-West', 'South Africa', 'Rustenburg', 'North-West', 'South Africa', '4310113883', 'vat_registered', 'freddie.mocke@valterraplatinum.com', 'Local'),
('CUS-00013', 'ArcelorMittal South Africa Limited LSP - Newcastle', 'ZAR', NULL, 'Lourches', 'France', NULL, NULL, 'France', '4920114990', 'vat_registered', NULL, 'Local'),
('2CO303', 'Ardagh Glass Packaging (Pty) Ltd - Clayville', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, 'South Africa', '4890235403', 'vat_registered', NULL, 'Local'),
('CUS-00015', 'Ardagh Glass Packaging (Pty) Ltd - Nigel', 'ZAR', NULL, 'Gauteng', 'South Africa', 'Pretoriusstad', 'Gauteng', 'Netherlands', '4890235403', 'vat_registered', 'gerrie.cloete@ardaghgroup.com', 'Local'),
('CUS-00016', 'Ardagh Glass Packaging (Pty) Ltd - Olifantsfontein', 'ZAR', NULL, NULL, 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4890235403', 'vat_registered', 'Vongani.Mkhabele@ardaghgroup.com', 'Local'),
('CUS-00017', 'Ardagh Glass Packaging (Pty) Ltd - Wadeville', 'ZAR', 'Germiston', 'Gauteng', 'South Africa', 'Germiston', 'Gauteng', 'South Africa', '4890235403', 'vat_registered', 'Neo.Leepile@ardaghgroup.com', 'Local'),
('CUS-00018', 'Assmang Iron Ore - Khumani Mine', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Kuruman', NULL, 'South Africa', '4310113883', 'vat_registered', 'Keitumetse.Komet@assmang.co.za', 'Local'),
('CUS-00019', 'Astec Industries South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4570189573', 'vat_registered', 'fventer@astecindustries.com', 'Local'),
('CUS-00020', 'Atlantica South Africa Operations (Pty) Ltd', 'ZAR', 'Upington', 'Northern Cape', 'South Africa', 'Upington', 'Northern Cape', NULL, '4470302003', 'vat_registered', 'gillnorishia.lategaan@abengoa.com', 'Local'),
('CUS-00021', 'Blendcor (Pty) Ltd', 'ZAR', 'Bluff', 'Kwazulu-Natal', 'South Africa', 'Bluff', 'Kwazulu-Natal', 'South Africa', '4730133743', 'vat_registered', 'Bobby.Pillay@blendcor.co.za', 'Local'),
('CUS-00022', 'Blue Mining Services (Pty) Ltd', 'ZAR', 'Middelburg', 'Mpumalanga', 'South Africa', 'Middelburg', 'Mpumalanga', 'South Africa', NULL, 'vat_not_registered', NULL, 'Local'),
('CUS-00023', 'Candex South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4870231125', 'vat_registered', 'palesa.mothale@alstomgroup.com', 'Local'),
('CUS-00024', 'CBI Electric African Cables (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Vereeniging', NULL, 'South Africa', '4750215859', 'vat_registered', 'enock.ngubane@cbi-electric.com', 'Local'),
('CUS-00025', 'City of Cape Town', 'ZAR', 'Bellville', 'Western Cape', 'South Africa', NULL, NULL, NULL, '4500193497', 'vat_registered', 'Siyabonga.Manyamalala@capetown.gov.za', 'Local'),
('CUS-00026', 'Clover SA (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4960141853', 'vat_registered', 'wesley.botes@clover.co.za', 'Local'),
('CUS-00027', 'CNNC Rössing Uranium', 'NAD', 'Arandis', 'Windhoek', 'Namibia', NULL, 'Arandis', 'Namibia', NULL, 'vat_not_registered', 'Kenneth.Strauss@Rossing.com.na', 'Overseas'),
('CUS-00028', 'Cofco International Standerton Oil Mills (Pty) Ltd', 'ZAR', 'Standerton', 'Mpumalanga', 'South Africa', 'Standerton', NULL, 'South Africa', '4780262830', 'vat_registered', 'BasilHolloway@cofcointernational.com', 'Local'),
('CUS-00029', 'Columbus Stainless (Pty) Ltd', 'ZAR', 'Middelburg', 'Mpumalanga', 'South Africa', 'Middelburg', 'Mpumalanga', 'South Africa', '4640196368', 'vat_registered', 'wilson.robin@columbus.co.za', 'Local'),
('CUS-00030', 'Concor Construction (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, 'South Africa', '4310110764', 'vat_registered', 'dave.timm@concor.co.za', 'Local'),
('CUS-00032', 'Corruseal Corrugated - Gauteng', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4130107297', 'vat_registered', 'thembi@corruseal.co.za', 'Local'),
('CUS-00033', 'D & S Crane & Plant Hire cc', 'ZAR', 'Richards Bay', 'Kwazulu-Natal', 'South Africa', NULL, NULL, 'Netherlands', NULL, 'vat_not_registered', 'admin@dands.co.za', 'Local'),
('CUS-00034', 'David Brown Santasalo SA (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Lockwood', NULL, 'United Kingdom', NULL, 'vat_not_registered', 'Thato.Diale@dbsantasalo.com', 'Local'),
('CUS-00035', 'De Aar Solar Power (RF) (Pty) Ltd', 'ZAR', 'Claremont', 'Western Cape', 'South Africa', 'De Aar', NULL, 'South Africa', '4920261817', 'vat_registered', 'sulana.dejager@globeleq.co.za', 'Local'),
('CUS-00036', 'De Beers Marine Namibia (Pty) Ltd', 'ZAR', 'Windhoek', 'Khomas Region', 'Namibia', 'Dr. Frans Indongo Street', NULL, 'Namibia', '4520131816', 'vat_registered', 'Jaco.vanHeerden@debmarine.com', 'Local'),
('CUS-00037', 'Diesel Innovations (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4330198146', 'vat_registered', NULL, 'Local'),
('CUS-00038', 'Drivetek Engineeing (Pty) Ltd', 'ZAR', 'Westmead', 'Kwazulu-Natal', 'South Africa', 'Westmead', 'Kwazulu-Natal', NULL, '4470284540', 'vat_registered', 'kevinw@technidrives.co.za', 'Local'),
('CUS-00039', 'DRS Innovative Mining Solutions', 'USD', 'Lubumbashi', 'Katanga', 'Democratic Republic of Congo', 'Mühlgasse 18-20', NULL, 'Germany', NULL, 'overseas', 'Marat.Tulegenov@ergafrica.com', 'Overseas'),
('CUS-00040', 'Dürr Africa (Pty) Ltd - Balancing & Assembly Products', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', NULL, 'vat_not_registered', NULL, 'Local'),
('CUS-00041', 'Dwarsrivier Chrome mine (Pty) Ltd', 'ZAR', 'Lydenburg', 'Limpopo', 'South Africa', 'Steelpoort', 'Limpopo', 'South Africa', '4210272078', 'vat_registered', 'jacoh@dwarsrivier.co.za', 'Local'),
('CUS-00042', 'Dynatec - Madagascar SA', 'USD', NULL, 'Toamasina', 'Madagascar', NULL, 'Toamasina', 'Madagascar', NULL, 'overseas', 'Manitra.Razafindraibe@ambatovy.mg', 'Overseas'),
('CUS-00043', 'Elite Truck Hire', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4130141197', 'vat_registered', 'lesleyp@elitetruck.co.za', 'Local'),
('CUS-00044', 'Engie - Peakers Operations (Pty) Ltd', 'ZAR', 'Durban', 'Kwazulu-Natal', 'South Africa', 'uMhlanga', 'Umhlanga Ridge', 'South Africa', '4580269977', 'vat_registered', 'natasha.james@engie.com', 'Local'),
('CUS-00045', 'Engie - Kathu Operations (Pty) Ltd', 'ZAR', 'Kathu', 'Northern Cape', 'South Africa', 'Kathu', 'Northern Cape', 'South Africa', '4420278790', 'vat_registered', 'nomathamsanqa.mdlela@engie.com', 'Local'),
('CUS-00046', 'Everest Equipment And Control cc', 'ZAR', 'Durban', 'Kwazulu-Natal', 'South Africa', NULL, NULL, NULL, NULL, 'vat_not_registered', 'ran@everestsa.net', 'Local'),
('CUS-00047', 'F Momberg BK t/a CMS Condition Monitoring Services', 'ZAR', 'Nelspruit (Mbombela)', 'Mpumalanga', 'South Africa', NULL, NULL, NULL, '4490194711', 'vat_registered', 'accounts@comoserv.com', 'Local'),
('CUS-00048', 'Firmenich (Pty) Ltd - Firsouth', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Hounslow', NULL, 'United Kingdom', '4760105330', 'vat_registered', 'morongoa.maponya@dsm-firmenich.com', 'Local'),
('CUS-00049', 'Firmenich (Pty) Ltd - Firzar', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Hounslow', NULL, 'United Kingdom', '4760105330', 'vat_registered', 'Sibongile.Maluleka@firmenich.com', 'Local'),
('CUS-00050', 'Fixturlaser South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4320268784', 'vat_registered', 'gerrit@fixturlaser.co.za', 'Local'),
('CUS-00051', 'FLSmidth SA - Saldanha', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, 'Madrid', 'Spain', '4620206328', 'vat_registered', 'lincoln.frank@flsmidth.com', 'Local'),
('CUS-00052', 'Fraser Alexander (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4860224031', 'vat_registered', 'KhumbulaniS@fraseralexander.co.za', 'Local'),
('CUS-00053', 'Fry''s Metals a division of LeadX (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4820314369', 'vat_registered', 'NkosinathiG@Frys.co.za', 'Local'),
('CUS-00054', 'GEA Africa (Pty) Ltd - Heating & Refrigeration Solutions Service', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', NULL, 'vat_not_registered', 'Langelihle.Mlovu@gea.com', 'Local'),
('CUS-00055', 'GEA Africa (Pty) Ltd - Sparta, Welkom', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', NULL, 'vat_not_registered', NULL, 'Local'),
('CUS-00056', 'Givaudan South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Tulisa Park', 'South Africa', 'Johannesburg South', 'Gauteng', 'South Africa', '4890107479', 'vat_registered', 'Nicole.davis@givaudan.com', 'Local'),
('CUS-00057', 'Glencore Marafe Venture - PSV Magareng Mine', 'ZAR', 'Rustenburg', 'North-West', 'South Africa', 'Rustenburg', 'North-West', 'South Africa', '4010216903', 'vat_registered', 'reinett.mohlala@glencore.co.za', 'Local'),
('CUS-00058', 'Glencore Merafe Join Venture - PSV Helena', 'ZAR', 'Steelpoort', 'Limpopo', 'South Africa', 'Steelpoort', 'Limpopo', 'South Africa', '4010216903', 'vat_registered', 'Cheryl-Ann.Bezuidenhout@glencore.co.za', 'Local'),
('CUS-00059', 'Glencore - PSV Lonmin EPL (UG2)', 'ZAR', 'Marikana', 'North West', 'South Africa', 'Marikana', 'North West', 'South Africa', NULL, 'vat_not_registered', NULL, 'Local'),
('CUS-00060', 'GRN Constructions Ltd', 'ZAR', 'Eggleston', 'Cobwebs', 'United Kingdom', 'Eggleston', 'Cobwebs', 'United Kingdom', NULL, 'overseas', 'purchase01@grnc21.com', 'Overseas'),
('CUS-00061', 'GZ Industries South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4760282196', 'vat_registered', 'Katlego.Moloko@gzican.com', 'Local'),
('CUS-00062', 'Harmony Moab Khotsong Operations (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, 'South Africa', '4250280130', 'vat_registered', NULL, 'Local'),
('CUS-00063', 'Heineken Beverages - Springs', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, 'Amsterdam', 'Netherlands', '4180211080', 'vat_registered', 'cherese.bosch@heineken.com', 'Local'),
('CUS-00064', 'Heineken Beverages - Wadeville', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Burgemeester Smeetsweg 1', NULL, 'Netherlands', '4180211080', 'vat_registered', 'Kabelo.bokgwathile@heineken.com', 'Local'),
('CUS-00065', 'Howden Africa Compressor and Turbines (HACT)', 'ZAR', 'Stikland', 'Western Cape', 'South Africa', 'Havelandseweg 8A', 'Industrieterrein Haveland', 'Netherlands', '4610118533', 'vat_registered', 'Caroline.Booysen@howden.co.za', 'Local'),
('CUS-00066', 'Hytec South Africa (RF) (Pty) Ltd - Richard''s Bay', 'ZAR', 'Richard''s Bay', 'KwaZulu-Natal', 'South Africa', 'Richard''s Bay', 'KwaZulu-Natal', 'South Africa', '4340213919', 'vat_registered', 'marius.froneman@boschrexroth.co.za', 'Local'),
('CUS-00067', 'Idwala Industrial Holdings (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4280211352', 'vat_registered', 'asp@idwala.co.za', 'Local'),
('CUS-00068', 'Illovo Sugar SA (Pty) Ltd - Eston', 'ZAR', NULL, 'Kwazulu-Natal', 'South Africa', 'Eston', NULL, 'South Africa', '4790254926', 'vat_registered', 'SibMkhwanazi@illovo.co.za', 'Local'),
('CUS-00069', 'Illovo Sugar SA (Pty) Ltd - Sezela', 'ZAR', 'Durban', 'Kwazulu-Natal', 'South Africa', NULL, NULL, 'South Africa', '4790254926', 'vat_registered', 'MaGovender@ILLOVO.co.za', 'Local'),
('CUS-00070', 'Impala Platinum Refineries Limited', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Springs', 'Geduld Proprietary Mines', 'South Africa', '4680121797', 'vat_registered', 'Brand.venter@implats.co.za', 'Local'),
('CUS-00071', 'Industrial Water Cooling (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4210112092', 'vat_registered', 'edwin@iwc.co.za', 'Local'),
('CUS-00072', 'Ingrain SA (Pty) Ltd - Bellville Mill', 'ZAR', 'Cape Town', 'Western Cape', 'South Africa', 'Cape Town', 'Western Cape', 'South Africa', '4670292392', 'vat_registered', 'Cheryl.Pearce@ingrainsa.com', 'Local'),
('CUS-00073', 'Ingrain SA (Pty) Ltd - Germiston Mill', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4670292392', 'vat_registered', 'Thembekile.Salman@ingrainsa.com', 'Local'),
('CUS-00074', 'Ingrain SA (Pty) Ltd - Kliprivier Mill', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Witkopdorp (Daleside', 'Daleside', 'South Africa', '4670292392', 'vat_registered', 'Tubi.Mokotong@ingrainsa.com', 'Local'),
('CUS-00075', 'Kalagadi Manganese (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4230235865', 'vat_registered', 'tebogo.maroeshe@kalagadi.co.za', 'Local'),
('CUS-00076', 'Karan Beef (Pty) Ltd - Balfour', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Balfour', NULL, 'South Africa', '4100174228', 'vat_registered', 'benniek@karanbeef.com', 'Local'),
('CUS-00077', 'Karan Beef (Pty) Ltd - City Deep', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg South', 'Gauteng', 'South Africa', '4100174228', 'vat_registered', 'Bhernard.Montgomery@karanbeef.com', 'Local'),
('CUS-00078', 'Kelvin Powerstation (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, 'United Kingdom', '4220193553', 'vat_registered', 'tenders@kelvinpower.com', 'Local'),
('CUS-00079', 'Kibali Gold Mine', 'USD', 'Kinshasa', 'Kinshasa', 'Democratic Republic of Congo', NULL, NULL, NULL, NULL, 'overseas', 'renet@wearcheck.co.za', 'Overseas'),
('CUS-00080', 'Kimberly Clark (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Copernicuslaan 35', NULL, 'Netherlands', '4220105342', 'vat_registered', 'abrahamchristoffelbraam.radley@kcc.com', 'Local'),
('CUS-00081', 'Knorr Bremse', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Rendementsweg 4N', NULL, 'Netherlands', '4430101404', 'vat_registered', 'rudi.durandt@knorr-bremse.com', 'Local'),
('CUS-00082', 'Kwena Mining Projects (Pty) Ltd', 'ZAR', 'Witbank', 'Mpumalanga', 'South Africa', 'Emalahleni', 'Mpumalanga', 'South Africa', '4260238870', 'vat_registered', 'chrisoost@kwenamining.co.za', 'Local'),
('CUS-00083', 'Lactalis South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4460149752', 'vat_registered', 'Jabulani-Christ.Memela@za.lactalis.com', 'Local'),
('CUS-00084', 'Marketech Consulting Engineers (Pty) Ltd', 'ZAR', 'Ashton-on-Ribble', 'Navigation Way', 'United Kingdom', 'Ashton-on-Ribble', 'Navigation Way', 'United Kingdom', '4130281724', 'vat_registered', 'jp@marketech.co.za', 'Local'),
('CUS-00085', 'Martin and Robson South Africa', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4610295372', 'vat_registered', NULL, 'Local'),
('CUS-00086', 'Eskom - Matimba Powerstation', 'ZAR', 'Lephalale', 'Limpopo', 'South Africa', 'Lephalale', 'Limpopo', 'South Africa', '4740101508', 'vat_registered', 'molaudr@eskom.co.za', 'Local'),
('CUS-00087', 'McCain Foods South Africa (Pty) Ltd - Delmas', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, 'South Africa', '4420188494', 'vat_registered', 'sabelo.mehlomakhulu@mccain.co.za', 'Local'),
('CUS-00088', 'McCain Foods South Africa (Pty) Ltd - Springs', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4420188494', 'vat_registered', 'carl.nel@mccain.co.za', 'Local'),
('CUS-00089', 'Mediclinic (Pty) Ltd - Stellenbosch', 'ZAR', 'Stellenbosch', 'Western Cape', 'South Africa', 'Stellenbosch', 'Western Cape', 'South Africa', '4760118184', 'vat_registered', 'audrey.govindasamy@mediclinic.co.za', 'Local'),
('CUS-00090', 'MediClinic(Pty) Ltd - Kloof', 'ZAR', 'Pretoria', 'Gauteng', 'South Africa', NULL, NULL, 'Belgium', '4190170326', 'vat_registered', 'Fhatuwani.Nemudivhiso@Mediclinic.co.za', 'Local'),
('CUS-00091', 'Middelburg Mine Services - Seriti Power (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Middelburg', 'R575', 'South Africa', '4850204555', 'vat_registered', NULL, 'Local'),
('CUS-00092', 'Modikwa Platinum Mine', 'ZAR', 'Driekop', 'Limpopo', 'South Africa', 'Burgersfort', 'Limpopo', 'South Africa', '4310113883', 'vat_registered', 'moses.mathopo@angloamerican.com', 'Local'),
('CUS-00093', 'Mondi South Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4330102007', 'vat_registered', 'pieter.bekker@mondigroup.com', 'Local'),
('CUS-00094', 'Mpact Operations (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, 'United Kingdom', '4590176527', 'vat_registered', 'KAmiappen@Mpact.co.za', 'Local'),
('CUS-00095', 'MpowerU Africa (Pty) Ltd', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Johannesburg', 'Gauteng', 'South Africa', '4920273176', 'vat_registered', 'charnel@mpoweru.co.za', 'Local'),
('CUS-00096', 'Msobo Coal (Pty) Ltd', 'ZAR', 'Breyten', 'Mpumalanga', 'South Africa', NULL, NULL, 'South Africa', '4030216297', 'vat_registered', 'rodney.white@northerncoal.co.za', 'Local'),
('CUS-00097', 'Nampak Products Ltd T/A Bevcan', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Oldends Lane', 'Severnside', 'United Kingdom', '4230113039', 'vat_registered', 'neels.vanderwesthuizen@nampak.com', 'Local'),
('CUS-00098', 'Nasonti Technical Services (Pty) Ltd - Goedehoop Colliery', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', NULL, NULL, NULL, '4450280922', 'vat_registered', 'Wesleyb@nasonti.com', 'Local'),
('CUS-00099', 'NDTS - Non Destructive Testing Services', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Van Slingelandtlaan 39', NULL, 'Netherlands', '4150150373', 'vat_registered', 'jeanpierrep@ndts.co.za', 'Local'),
('CUS-00100', 'Nedbank Limited - Bloemfontein', 'ZAR', 'Johannesburg', 'Gauteng', 'South Africa', 'Bloemfontein', 'Free State', 'South Africa', '4320116074', 'vat_registered', 'TebohoMa@nedbank.co.za', 'Local');

-- Continue with more customers in next batch...
