-- Real Personnel Data for Equipment Store
-- Run this to replace mock data with actual WearCheck personnel

-- Clear existing personnel (this will fail if there are movements referencing them)
-- If you have existing movements, we'll just add new personnel instead
DELETE FROM personnel WHERE employee_id LIKE 'EMP%';

-- Insert real personnel data
INSERT INTO personnel (employee_id, full_name, email, department) VALUES
    ('WC492', 'Adri Ludick', NULL, 'GP Consult'),
    ('WC383', 'Adriaan Pertus Johannes Bouwer', NULL, 'WearCheck'),
    ('WEC094', 'Ailwel Marshall Rasimphi', NULL, 'GP Consult'),
    ('WEC105', 'Alexander Outram', NULL, 'GP Consult'),
    ('WEC123', 'Allan Stuurman', NULL, 'GP Consult'),
    ('WC511', 'André Erasmus', NULL, 'AFS'),
    ('WEC103', 'Andrew John Walker Robb', NULL, 'GP Consult'),
    ('WC484', 'Annah Seipone Modutwane', NULL, 'WearCheck'),
    ('WC319', 'Annemie Willer', NULL, 'WearCheck'),
    ('WC503', 'Antonio Ehrke', NULL, 'AFS'),
    ('UNK001', 'Armindo Muchacho', NULL, 'WearCheck'),
    ('WC526', 'Arnoldus Johannes van Zyl', NULL, 'AFS'),
    ('WEC114', 'Aubrey Tshabalala', NULL, 'GP Consult'),
    ('UNK002', 'Benedito Timana', NULL, 'WearCheck'),
    ('WEC052', 'Boitumelo Ngokoana Makgamatha', NULL, 'GP Consult'),
    ('WC380', 'Chicco Fransisco Tivane', NULL, 'WearCheck'),
    ('WEC100', 'Chris Mostert', NULL, 'GP Consult'),
    ('WC285', 'Christene Smal', NULL, 'WearCheck'),
    ('WEC120', 'CJ Woller', NULL, 'GP Consult'),
    ('WC486', 'Colleen Pyper', NULL, 'AFS'),
    ('WC528', 'Daniel Greef Meintjies', NULL, 'AFS'),
    ('WC402', 'Tshegofatsho Daniel Molapo', NULL, 'GP Consult'),
    ('WEC081', 'David Viljoen', NULL, 'GP Consult'),
    ('UNK003', 'David Lipague', NULL, 'WearCheck'),
    ('WC358', 'Deon Gaarkeuken', NULL, 'WearCheck'),
    ('WEC086', 'Desmond Ngomane', NULL, 'GP Consult'),
    ('WCN008', 'Dian Leff', NULL, 'WearCheck'),
    ('WEC119', 'Douglas Prout-Jones', NULL, 'GP Consult'),
    ('WEC122', 'Eben Prinsloo', NULL, 'GP Consult'),
    ('WC274', 'Edward Frederick IV Pieterse', NULL, 'WearCheck'),
    ('WC271', 'Edward Pieterse', NULL, 'WearCheck'),
    ('WEC138', 'Edwin Ashley Gibbons', NULL, 'AFS'),
    ('WC488', 'Ethel Mienie', NULL, 'AFS'),
    ('WEC090', 'Eugene Scheepers', NULL, 'GP Consult'),
    ('WC497', 'Evert Viljoen', NULL, 'AFS'),
    ('WEC080', 'Michael Francios Pretorius', NULL, 'GP Consult'),
    ('WC287', 'Francois Jacobus van Eeden', NULL, 'WearCheck'),
    ('WEC111', 'Jozua Francois Joubert Pienaar', NULL, 'GP Consult'),
    ('WCN004', 'Freddy-Ben Gariseb', NULL, 'WearCheck'),
    ('WCN007', 'Gabriel Shikongo Nuunyango', NULL, 'WearCheck'),
    ('WC510', 'Godfrey Boikhutso', NULL, 'AFS'),
    ('WEC093', 'Gordon John Frederick Hoy', NULL, 'GP Consult'),
    ('WC270', 'Gustav Lourens', NULL, 'WearCheck'),
    ('WEC047', 'Hannest Koegelenberg', NULL, 'GP Consult'),
    ('WEC129', 'Hein Coetzer', NULL, 'GP Consult'),
    ('WEC134', 'Fritz Kusel', NULL, 'GP Consult'),
    ('WEC098', 'Henry Mherekumombe', NULL, 'GP Consult'),
    ('UNK004', 'Isac Zacarias', NULL, 'WearCheck'),
    ('WC493', 'Jacobus Frederick Venter', NULL, 'AFS'),
    ('WC352', 'Jacobus Johannes Willer', NULL, 'WearCheck'),
    ('WEC097', 'Theunis Gerhardus Jacobus de Beer', NULL, 'GP Consult'),
    ('WC236', 'James Papayito Tshabalala', NULL, 'WearCheck'),
    ('WC496', 'Jan Booysens', NULL, 'AFS'),
    ('WC494', 'Johann Louw', NULL, 'AFS'),
    ('WEC137', 'Jean Jacques de Beer', NULL, 'GP Consult'),
    ('WC645', 'Johan Bekker', NULL, 'AFS'),
    ('WC491', 'Johan Rossouw', NULL, 'AFS'),
    ('WC508', 'Johannes Gideon Francios Stols', NULL, 'AFS'),
    ('WEC089', 'Johannes Andréas Oosthuizen', NULL, 'GP Consult'),
    ('WC531', 'Joseph Benjamin Kies', NULL, 'AFS'),
    ('WC527', 'Jean-Pierre Jordaan', NULL, 'AFS'),
    ('WEC135', 'Kevin Henwood', NULL, 'GP Consult'),
    ('WC482', 'Khotso Thabo Mosala', NULL, 'AFS'),
    ('WC455', 'Leon Coetzee', NULL, 'WearCheck'),
    ('WEC126', 'Lesego Khuthwane', NULL, 'GP Consult'),
    ('WC495', 'Lorraine Lerato Mokgethi', NULL, 'AFS'),
    ('WC648', 'Londolani Managa', NULL, 'WearCheck'),
    ('WC269', 'Bernard Lopi Molangoane', NULL, 'WearCheck'),
    ('WC277', 'Louis Robert Peacock', NULL, 'WearCheck'),
    ('WEC118', 'Labby Jeffrey Lubis', NULL, 'GP Consult'),
    ('WEC068', 'Lucas Johannes Bartel Luus', NULL, 'GP Consult'),
    ('WEC116', 'Mandé Coetzee', NULL, 'GP Consult'),
    ('WEC102', 'Marcel Schoeman', NULL, 'GP Consult'),
    ('WEC109', 'Mariette du Rand', NULL, 'GP Consult'),
    ('WEC106', 'Marthinus Jacobus van Aarde', NULL, 'GP Consult'),
    ('WC483', 'Mike Mbongeni Shongwe', NULL, 'AFS'),
    ('WEC104', 'Megan Salzwedel', NULL, 'GP Consult'),
    ('WC536', 'Mervyn Thomas Gibbons', NULL, 'AFS'),
    ('WEC088', 'Meshack Welcome Nxumalo', NULL, 'GP Consult'),
    ('WEC076', 'Micheal Francios Pretorius', NULL, 'GP Consult'),
    ('WC291', 'Seporo Micheal Masemola', NULL, 'WearCheck'),
    ('WC465', 'Mmatapa Betty Monyepao', NULL, 'WearCheck'),
    ('WC361', 'Mórne Alberts', NULL, 'WearCheck'),
    ('WEC113', 'Nadhira Bux', NULL, 'GP Consult'),
    ('WC506', 'Nicolaas du Plessis', NULL, 'AFS'),
    ('UNK005', 'Muhamad Hanif', NULL, 'WearCheck'),
    ('WEC099', 'Lloyd Ngobeni', NULL, 'GP Consult'),
    ('WC651', 'Nomvula Mkhize', NULL, 'WearCheck'),
    ('WC509', 'Norman Landus Walters', NULL, 'AFS'),
    ('WC348', 'Putaneng Paswell Mashoeu', NULL, 'WearCheck'),
    ('WC498', 'Patrick Nel', NULL, 'AFS'),
    ('WC520', 'Petrus Johannes Peacock', NULL, 'WearCheck'),
    ('WEC115', 'Percy Hall', NULL, 'GP Consult'),
    ('WC393', 'Katishi Permission Malele', NULL, 'WearCheck'),
    ('UNK006', 'Peter Ivo Mateus Mahlangu', NULL, 'WearCheck'),
    ('WC253', 'Philippus Jacobus Wilhelmus Schutte', NULL, 'WearCheck'),
    ('UNK007', 'Placido Maculuve', NULL, 'WearCheck'),
    ('WEC074', 'Rakcal Monroe Balaram', NULL, 'GP Consult'),
    ('WC382', 'Reinier Kalp', NULL, 'WearCheck'),
    ('WC591', 'Adriaan Johannes du Plooy', NULL, 'WearCheck'),
    ('WC363', 'Riaan de Beer', NULL, 'WearCheck'),
    ('WC507', 'Richard van Vuuren', NULL, 'AFS'),
    ('WC504', 'Roger Henwood', NULL, 'AFS'),
    ('WC381', 'Hermanus Johannes Willer', NULL, 'WearCheck'),
    ('WEC096', 'Rynhardt Meyer', NULL, 'GP Consult'),
    ('WC501', 'Rynhardt Smit', NULL, 'AFS'),
    ('WC264', 'Sergant Sakhile Tlou', NULL, 'WearCheck'),
    ('WEC136', 'Shaun Janse van Rensburg', NULL, 'GP Consult'),
    ('WEC130', 'Shivon Chantelle Alberts', NULL, 'GP Consult'),
    ('WC283', 'Mokale Simon Mosima', NULL, 'WearCheck'),
    ('WC485', 'Simon Petrus Difutso', NULL, 'AFS'),
    ('WC360', 'Sipho Petros Zwane', NULL, 'GP Consult'),
    ('WEC039', 'Sipho Petros Mathibela', NULL, 'GP Consult'),
    ('WC487', 'Teresa Venter', NULL, 'AFS'),
    ('WEC132', 'Thapelo Pebetsi Mohlala', NULL, 'GP Consult'),
    ('WC243', 'Thomas Mdhlala', NULL, 'WearCheck'),
    ('WEC062', 'Thulani Tembe', NULL, 'GP Consult'),
    ('WEC057', 'Tonny Simelani', NULL, 'GP Consult'),
    ('WEC133', 'Tsietsi Petric Monnanyane', NULL, 'GP Consult'),
    ('WEC124', 'Vernon Calvert', NULL, 'GP Consult'),
    ('WEC127', 'Wihan Manu Willer', NULL, 'GP Consult');

-- Verify the import
SELECT COUNT(*) as total_personnel FROM personnel;
